# Generated by Django 6.0.7 on 2026-07-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Restoran', 'Restoran'), ('Kafe', 'Kafe'), ('Fitness', 'Fitness'), ('Barber', 'Barber'), ('Salon', 'Salon'), ('Avto', 'Avto'), ('Tibbiyot', 'Tibbiyot'), ('Shifoxona', 'Shifoxona'), ("Ta'lim", "Ta'lim"), ('Taxi', 'Taxi')], max_length=32)),
                ('business_type', models.CharField(choices=[('YaTT', 'YaTT (Yakka tartibli tadbirkor)'), ('MChJ', 'MChJ'), ('OK', 'Oilaviy korxona')], default='YaTT', max_length=8)),
                ('stir', models.CharField(blank=True, max_length=16)),
                ('owner', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=64)),
                ('telegram', models.CharField(blank=True, max_length=64)),
                ('website', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('work_days', models.CharField(blank=True, default='Dushanba – Juma', max_length=64)),
                ('work_hours', models.CharField(blank=True, default='09:00 - 18:00', max_length=64)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount_scope', models.CharField(default='Barcha mahsulotlar', max_length=64)),
                ('login', models.CharField(blank=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('document_name', models.CharField(blank=True, max_length=128)),
                ('document_size_kb', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Tasdiqlangan', 'Tasdiqlangan'), ('Kutilmoqda', 'Kutilmoqda'), ('Takroriy', 'Takroriy'), ('Rad etilgan', 'Rad etilgan'), ('Bloklangan', 'Bloklangan')], default='Kutilmoqda', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('block_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateField()),
                ('registered_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Restoran', 'Restoran'), ('Kafe', 'Kafe'), ('Fitness', 'Fitness'), ('Barber', 'Barber'), ('Salon', 'Salon'), ('Avto', 'Avto'), ('Tibbiyot', 'Tibbiyot'), ('Shifoxona', 'Shifoxona'), ("Ta'lim", "Ta'lim"), ('Taxi', 'Taxi')], max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=64)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda"), ("Bog'lanildi", "Bog'lanildi"), ('Biznes yaratildi', 'Biznes yaratildi'), ('Rad etildi', 'Rad etildi')], default='Yangi', max_length=32)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('daily_active', models.PositiveIntegerField(default=0)),
                ('qr_scans', models.PositiveIntegerField(default=0)),
                ('peak_hour', models.PositiveIntegerField(default=18)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Premium', 'Premium'), ('Yangi', 'Yangi'), ("Muddati o'tgan", "Muddati o'tgan"), ('Free Trial', 'Free Trial')], default='Yangi', max_length=20)),
                ('activity_status', models.CharField(choices=[('Faol', 'Faol'), ('Nofaol', 'Nofaol'), ('Yangi', 'Yangi'), ("O'tgan", "O'tgan")], default='Faol', max_length=20)),
                ('joined_at', models.DateField()),
                ('savings_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('membership_start', models.DateField(blank=True, null=True)),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('months_subscribed', models.PositiveIntegerField(default=0)),
                ('device', models.CharField(blank=True, max_length=64)),
                ('push_enabled', models.BooleanField(default=True)),
                ('referral_code', models.CharField(blank=True, max_length=16)),
                ('referral_invited', models.PositiveIntegerField(default=0)),
                ('referral_target', models.PositiveIntegerField(default=3)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=150)),
                ('block_comment', models.TextField(blank=True)),
                ('blocked_at', models.DateField(blank=True, null=True)),
                ('extended_at', models.DateField(blank=True, null=True)),
                ('extend_reason', models.CharField(blank=True, max_length=150)),
                ('extend_months', models.PositiveIntegerField(default=0)),
                ('churn_reason', models.CharField(blank=True, choices=[("To'lov muddati o'tib ketgan", "To'lov muddati o'tib ketgan"), ('Narxi qimmat', 'Narxi qimmat'), ('Boshqa ilova ishlatmoqda', 'Boshqa ilova ishlatmoqda'), ('Boshqa sabab', 'Boshqa sabab')], max_length=64)),
            ],
            options={
                'ordering': ['-joined_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('payment_page_opens', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('business_application', 'Biznes arizasi'), ('member_joined', "Yangi a'zo"), ('push_sent', 'Push yuborildi'), ('business_approved', 'Biznes tasdiqlandi')], default='business_application', max_length=32)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=150)),
                ('cashier', models.CharField(blank=True, max_length=64)),
                ('original_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('Muvaffaqiyatli', 'Muvaffaqiyatli'), ('Bekor qilingan', 'Bekor qilingan')], default='Muvaffaqiyatli', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.business')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('audience_type', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('premium', "Premium a'zolar"), ('category', "Kategoriya bo'yicha"), ('individual', 'Alohida odam')], default='all', max_length=16)),
                ('category', models.CharField(blank=True, choices=[('Restoran', 'Restoran'), ('Kafe', 'Kafe'), ('Fitness', 'Fitness'), ('Barber', 'Barber'), ('Salon', 'Salon'), ('Avto', 'Avto'), ('Tibbiyot', 'Tibbiyot'), ('Shifoxona', 'Shifoxona'), ("Ta'lim", "Ta'lim"), ('Taxi', 'Taxi')], max_length=32)),
                ('language', models.CharField(default='uz', max_length=8)),
                ('send_time', models.CharField(default='Hozir', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.member')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=32, unique=True)),
                ('user_display_name', models.CharField(max_length=150)),
                ('months', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('method', models.CharField(choices=[('Click', 'Click'), ('Payme', 'Payme'), ('Humo/Uzcard', 'Humo/Uzcard')], max_length=16)),
                ('status', models.CharField(choices=[('Muvaffaqiyatli', 'Muvaffaqiyatli'), ('Kutilmoqda', 'Kutilmoqda'), ('Qaytarilgan', 'Qaytarilgan')], max_length=20)),
                ('psp_ref', models.CharField(blank=True, max_length=32)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, max_length=150)),
                ('refund_comment', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
