# Generated by Django 6.0.7 on 2026-07-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformstat',
            name='registrations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
