# Generated by Django 6.0.7 on 2026-07-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformstat_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapplication',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='business_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='created_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_applications', to='core.business'),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='discount_scope',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='district',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='instagram',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='login',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='min_purchase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='telegram',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='website',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='work_days',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='work_hours',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda"), ("Bog'lanildi", "Bog'lanildi"), ('Tasdiqlangan', 'Tasdiqlangan'), ('Biznes yaratildi', 'Biznes yaratildi'), ('Rad etildi', 'Rad etildi')], default='Yangi', max_length=32),
        ),
    ]
