# Generated by Django 6.0.7 on 2026-07-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business_latitude_business_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminalert',
            name='kind',
            field=models.CharField(choices=[('business_application', 'Biznes arizasi'), ('member_joined', "Yangi a'zo"), ('push_sent', 'Push yuborildi'), ('business_approved', 'Biznes tasdiqlandi'), ('business_request', "Biznes so'rovi")], default='business_application', max_length=32),
        ),
    ]
