# Generated by Django 6.0.7 on 2026-07-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adminalert_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(default='discount_request', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('old_percent', models.PositiveIntegerField(default=0)),
                ('new_percent', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan')], default='Kutilmoqda', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
