# Generated by Django 6.0.7 on 2026-07-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_businessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=64, unique=True)),
                ('member_name', models.CharField(max_length=150)),
                ('member_phone', models.CharField(blank=True, max_length=32)),
                ('invited_count', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan')], default='Kutilmoqda', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='adminalert',
            name='kind',
            field=models.CharField(choices=[('business_application', 'Biznes arizasi'), ('member_joined', "Yangi a'zo"), ('push_sent', 'Push yuborildi'), ('business_approved', 'Biznes tasdiqlandi'), ('business_request', "Biznes so'rovi"), ('referral_request', "Referal so'rovi")], default='business_application', max_length=32),
        ),
    ]
