# Generated by Django 6.0.7 on 2026-07-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_referralrequest_alter_adminalert_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='core.member'),
        ),
    ]
