# Generated by Django 6.0.7 on 2026-07-29 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_referralrequest_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminalert',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.member'),
        ),
    ]
