# Generated by Django 6.0.7 on 2026-07-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryactivitystat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stats', to='businesses.category'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryactivitystat',
            unique_together={('date', 'category')},
        ),
    ]
