# Generated by Django 6.0.7 on 2026-07-11 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_initial'),
        ('discounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountchangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_discount_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='businesses.cashier'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['business', 'used_at'], name='discounts_d_busines_eef920_idx'),
        ),
    ]
