# Generated by Django 6.0.7 on 2026-07-28 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_application_panel_login_application_panel_password'),
        ('discounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Standart', 'Standart'), ('Premium', 'Premium'), ('Maxsus taklif', 'Maxsus taklif'), ('VIP', 'VIP'), ("Tug'ilgan kun", "Tug'ilgan kun")], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('percent', models.PositiveSmallIntegerField()),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='businesses.business')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('business', 'category'), name='uniq_business_discount_category')],
            },
        ),
    ]
