# Generated by Django 6.0.7 on 2026-08-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountchangerequest',
            name='action',
            field=models.CharField(choices=[('percent', "Asosiy foizni o'zgartirish"), ('create', "Yangi chegirma qo'shish"), ('update', 'Chegirmani tahrirlash')], default='percent', max_length=12),
        ),
        migrations.AddField(
            model_name='discountchangerequest',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='discountchangerequest',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='discountchangerequest',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='discountchangerequest',
            name='new_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discountchangerequest',
            name='new_min_purchase',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
