# Generated by Django 6.0.7 on 2026-07-11 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('yatt', 'YaTT'), ('mchj', 'MCHJ')], max_length=10)),
                ('responsible_full_name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=150)),
                ('telegram', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('region', models.CharField(max_length=120)),
                ('city_district', models.CharField(max_length=120)),
                ('full_address', models.CharField(max_length=500)),
                ('work_days', models.CharField(choices=[('mon_fri', 'Dushanba - Juma'), ('mon_sat', 'Dushanba - Shanba'), ('everyday', 'Har kuni')], default='everyday', max_length=20)),
                ('work_hours_from', models.TimeField(blank=True, null=True)),
                ('work_hours_to', models.TimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=10)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Barcha mahsulotlar'), ('min_purchase', 'Minimal xarid summasi')], default='fixed', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('yatt', 'YaTT'), ('mchj', 'MCHJ')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=150)),
                ('telegram', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('region', models.CharField(max_length=120)),
                ('city_district', models.CharField(max_length=120)),
                ('full_address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('partnership_status', models.CharField(choices=[('active', 'Faol hamkorlik'), ('paused', "To'xtatilgan"), ('stopped', 'Bekor qilingan')], default='active', max_length=20)),
                ('contract_signed', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
