# Generated by Django 6.0.7 on 2026-07-12 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak (masalan: +998900000000).", regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.CharField(choices=[('tashkent_city', 'Toshkent shahar'), ('tashkent_region', 'Toshkent viloyati'), ('andijan', 'Andijon'), ('bukhara', 'Buxoro'), ('fergana', "Farg'ona"), ('jizzakh', 'Jizzax'), ('kashkadarya', 'Qashqadaryo'), ('navoiy', 'Navoiy'), ('namangan', 'Namangan'), ('samarkand', 'Samarqand'), ('surkhandarya', 'Surxondaryo'), ('sirdaryo', 'Sirdaryo'), ('khorezm', 'Xorazm'), ('karakalpakstan', "Qoraqalpog'iston")], max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak (masalan: +998900000000).", regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='business',
            name='region',
            field=models.CharField(choices=[('tashkent_city', 'Toshkent shahar'), ('tashkent_region', 'Toshkent viloyati'), ('andijan', 'Andijon'), ('bukhara', 'Buxoro'), ('fergana', "Farg'ona"), ('jizzakh', 'Jizzax'), ('kashkadarya', 'Qashqadaryo'), ('navoiy', 'Navoiy'), ('namangan', 'Namangan'), ('samarkand', 'Samarqand'), ('surkhandarya', 'Surxondaryo'), ('sirdaryo', 'Sirdaryo'), ('khorezm', 'Xorazm'), ('karakalpakstan', "Qoraqalpog'iston")], max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
