# Generated by Django 6.0.7 on 2026-07-12 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_application_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5, message="Chegirma foizi kamida 5%% bo'lishi kerak."), django.core.validators.MaxValueValidator(100, message='Chegirma foizi 100%% dan oshmasligi kerak.')]),
        ),
    ]
