# Generated by Django 6.0.7 on 2026-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='panel_login',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='panel_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
