# Generated by Django 6.0.7 on 2026-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_application_panel_login_application_panel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='login',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cashier',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='cashier',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
