# Generated by Django 6.0.7 on 2026-07-13 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_application_applicant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Mijoz nomi')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Mijoz telefoni')),
                ('service_name', models.CharField(help_text='Masalan: Soch olish, Soqul qilish, Soch + Soqul', max_length=200, verbose_name='Xizmat nomi')),
                ('service_category', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asl narx')),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma foizi (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chegirma miqdori')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'lanagan narx")),
                ('status', models.CharField(choices=[('completed', 'Amalga oshirildi'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Refund qilindi')], default='completed', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Yaratildi'), ('updated', 'Yangilandi'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Refund qilindi')], max_length=20, verbose_name='Harakat')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Eski qiymatlar')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Yangi qiymatlar')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirildi")),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Tranzaksiya logi',
                'verbose_name_plural': 'Tranzaksiya logları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyTransactionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Jami tranzaksiyalar')),
                ('total_base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami asl narxi')),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami chegirma')),
                ('total_final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Jami to'lanagan")),
                ('average_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="O'rtacha chegirma %")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Kunlik statistika',
                'verbose_name_plural': 'Kunlik statistikalar',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['business', '-date'], name='transaction_busines_c1b52d_idx')],
                'unique_together': {('business', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['business', '-created_at'], name='transaction_busines_04ca19_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['cashier', '-created_at'], name='transaction_cashier_cbf652_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
    ]
