# Generated by Django 6.0.7 on 2026-08-05 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_profilechangerequest'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz (hisob)'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', '-created_at'], name='transaction_custome_8b8f5a_idx'),
        ),
    ]
